var fullName = 'Omid Asadi';
var isCool = true;
var totalPets = 4;
var unknown = null;
var never;
console.log('fullName: ', fullName);
console.log('typeof fullName: ', typeof fullName);
console.log('isCool: ', isCool);
console.log('typeof isCool: ', typeof isCool);
console.log('totalPets: ', totalPets);
console.log('typeof totalPets: ', typeof totalPets);
console.log('unknown: ', unknown);
console.log('typeof unknown: ', typeof unknown);
console.log('never: ', never);
console.log('typeof never: ', typeof never);
