var width = 2;
var height = 5;
var area = width * height;
console.log('Value of Area: ', area);
console.log('typeof Area: ', typeof area);
var bill = 1000;
var payment = 1100;
var change = payment - bill;
console.log('Value of change: ', change);
console.log('typeof change: ', typeof change);
var quizzes = 50;
var midterm = 90;
var final = 100;
var grade = (quizzes + midterm + final) / 3;
console.log('Value of grade: ', grade);
console.log('typeof grade: ', typeof grade);
var firstName = 'Omid';
var lastName = 'Asadi';
var fullName = firstName + ' ' + lastName;
console.log('Value of fullName: ', fullName);
console.log('typeof fullName: ', typeof fullName);
var pH = 10;
var isAcidic = pH < 7;
console.log('Value of isAcidic: ', isAcidic);
console.log('typeof isAcidic: ', typeof isAcidic);
var headCount = 11;
var isSparta = headCount === 300;
console.log('Value of isSparta: ', isSparta);
console.log('typeof isSparta: ', typeof isSparta);
var motto = fullName;
motto += ' is the GOAT';
console.log('Value of motto: ', motto);
console.log('tyoeof motto: ', typeof motto);
